# Generated by Django 2.1.5 on 2019-01-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=200, verbose_name='Название альбома')),
            ],
            options={
                'verbose_name_plural': 'Фотоальбомы',
                'verbose_name': 'Фотоальбом',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Наименование категории')),
                ('category_description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('dish_name', models.CharField(max_length=200, verbose_name='Наименование блюда (рус.)')),
                ('dish_eng_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование блюда (англ.)')),
                ('dish_price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость блюда')),
                ('dish_description', models.TextField(blank=True, null=True, verbose_name='Описание блюда')),
                ('dish_weight', models.IntegerField(blank=True, verbose_name='Масса блюда')),
                ('dish_type', models.CharField(choices=[('d', 'Еда'), ('b', 'Напиток')], default='d', max_length=1, verbose_name='Тип блюда')),
                ('dish_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_dishes', to='main.Category', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name_plural': 'Блюда',
                'verbose_name': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_name', models.CharField(blank=True, max_length=200, verbose_name='Название фотографии')),
                ('foto_img', models.ImageField(blank=True, upload_to='images', verbose_name='Фотография')),
                ('foto_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_fotos', to='main.Album', verbose_name='Альбом фотографии')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
                'verbose_name': 'Фотография',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=200, verbose_name='Наименование подкатегории')),
                ('subcategory_description', models.TextField(blank=True, verbose_name='Описание подкатегории')),
                ('subcategory_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_subcategories', to='main.Category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name_plural': 'Подкатегории',
                'verbose_name': 'Подкатегория',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_dishes', to='main.SubCategory', verbose_name='Подкатегория блюда'),
        ),
    ]
