# Generated by Django 2.1.5 on 2019-01-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190109_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sorting',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='sorting',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='foto',
            name='sorting',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sorting',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
