# Generated by Django 2.1.5 on 2019-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190110_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sorting'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['sorting'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sorting'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='sorting',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sorting',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sorting',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
    ]
