# Generated by Django 2.1.5 on 2019-01-11 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('main', '0005_auto_20190110_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес в подвале')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='sorting',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
    ]
