# Generated by Django 2.1.5 on 2019-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190111_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prpreferences',
            options={'verbose_name': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='prpreferences',
            name='address_in_contacts',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес в контактах'),
        ),
        migrations.AlterField(
            model_name='prpreferences',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес в подвале'),
        ),
    ]
