# Generated by Django 2.1.5 on 2019-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190111_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='prpreferences',
            name='slides_speed',
            field=models.IntegerField(blank=True, default=2000, verbose_name='Скорость смены слайдов на главной (в мс)'),
        ),
    ]
