# Generated by Django 2.1.5 on 2019-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_prpreferences_slides_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='prpreferences',
            name='slides_speed',
            field=models.IntegerField(blank=True, default=2000, verbose_name='Скорость смены фоновых слайдов (в мс)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
