# Generated by Django 2.1.5 on 2019-01-12 09:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190112_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='prpreferences',
            name='about_us_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст о нас (HTML)'),
        ),
    ]
