# Generated by Django 2.1.5 on 2019-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_prpreferences_about_us_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='published',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена блюда'),
        ),
    ]
