# Generated by Django 2.1.5 on 2019-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190114_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='prpreferences',
            name='booking_meta_desc',
            field=models.TextField(blank=True, verbose_name='Тег meta-description страницы с формой бронирования стола'),
        ),
        migrations.AddField(
            model_name='prpreferences',
            name='contacts_meta_desc',
            field=models.TextField(blank=True, verbose_name='Тег meta-description страницы с контактами'),
        ),
        migrations.AddField(
            model_name='prpreferences',
            name='index_meta_desc',
            field=models.TextField(blank=True, verbose_name='Тег meta-description главной страницы'),
        ),
    ]
